name: geog777-lab1
channels:
  - defaults
dependencies:
  - astroid=2.3.3=py38_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2019.11.28=py38_0
  - click=7.0=py_0
  - curl=7.67.0=ha441bb4_0
  - expat=2.2.6=h0a44026_0
  - flask=1.1.1=py_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - freexl=1.0.5=h1de35cc_0
  - gdal=2.3.3=py38hbe65578_0
  - geos=3.7.1=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - giflib=5.1.4=h1de35cc_1
  - glib=2.63.1=hd977a24_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.4=233
  - isort=4.3.21=py38_0
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=he5867d9_2
  - json-c=0.13.1=h3efe00b_0
  - kealib=1.4.7=hf5ed860_6
  - krb5=1.16.4=hddcf347_0
  - lazy-object-proxy=1.4.3=py38h1de35cc_0
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.67.0=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libdap4=3.19.1=h3d3e54a_0
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgdal=2.3.3=h0950a36_0
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libkml=1.3.0=hbe12b63_4
  - libnetcdf=4.6.1=hd5207e6_2
  - libpng=1.6.37=ha441bb4_0
  - libpq=11.2=h051b688_0
  - libspatialite=4.3.0a=h644ec7d_19
  - libssh2=1.8.2=ha12b0ac_0
  - libtiff=4.1.0=hcb84e12_0
  - libxml2=2.9.9=hf6e021a_1
  - markupsafe=1.1.1=py38h1de35cc_0
  - mccabe=0.6.1=py38_1
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.0.15=py38h5e564d8_0
  - mkl_random=1.1.0=py38h6440ff4_0
  - ncurses=6.1=h0a44026_1
  - numpy-base=1.18.1=py38h6575580_1
  - openjpeg=2.3.0=hb95cd4c_1
  - openssl=1.1.1d=h1de35cc_4
  - pcre=8.43=h0a44026_0
  - pip=20.0.2=py38_1
  - pixman=0.38.0=h1de35cc_0
  - poppler=0.65.0=ha097c24_1
  - poppler-data=0.4.9=0
  - proj4=5.2.0=h0a44026_1
  - pylint=2.4.4=py38_0
  - python=3.8.1=h359304d_1
  - readline=7.0=h1de35cc_5
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py38_0
  - wrapt=1.11.2=py38h1de35cc_0
  - xerces-c=3.2.2=h44e365a_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - affine==2.3.0
    - attrs==19.3.0
    - click-plugins==1.1.1
    - cligj==0.5.0
    - datetime==4.3
    - fiona==1.8.13.post1
    - geopandas==0.7.0
    - munch==2.5.0
    - numpy==1.18.1
    - pandas==1.0.1
    - patsy==0.5.1
    - pyparsing==2.4.6
    - pyproj==2.5.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - rasterio==1.1.2
    - rasterstats==0.14.0
    - scipy==1.4.1
    - shapely==1.7.0
    - simplejson==3.17.0
    - snuggs==1.4.7
    - statsmodels==0.11.1
    - zope-interface==4.7.1
prefix: /usr/local/anaconda3/envs/geog777-lab1

